# Generated by Django 5.1.7 on 2025-03-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
